### ISSUE TITLE
ci_reporter does not work with minitest >= 5.0.0

### ISSUE THREAD

**Issue by okitan** [ci-reporter/ci_reporter#110]
```
/Users/okitan/.rvm/rubies/ruby-2.0.0-p0/bin/ruby -Ilib -I/Users/okitan/.rvm/gems/ruby-2.0.0-p0@global/gems/bundler-1.3.4/lib -rbundler/setup -rci/reporter/rake/minitest_loader acceptance/minite
st_example_test.rb
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /Users/okitan/codes/ci_reporter/lib/ci/reporter/minitest.rb:7:in `require'
  /Users/okitan/codes/ci_reporter/lib/ci/reporter/minitest.rb:7:in `<top (required)>'
  /Users/okitan/codes/ci_reporter/lib/ci/reporter/rake/minitest_loader.rb:6:in `require'
  /Users/okitan/codes/ci_reporter/lib/ci/reporter/rake/minitest_loader.rb:6:in `<top (required)>'
  acceptance/minitest_example_test.rb:1:in `require'
/Users/okitan/codes/ci_reporter/lib/ci/reporter/rake/minitest_loader.rb:9:in `<top (required)>': undefined method `runner=' for Minitest::Unit:Class (NoMethodError)
        from acceptance/minitest_example_test.rb:1:in `require'
Failures above are expected.
/Users/okitan/.rvm/rubies/ruby-2.0.0-p0/bin/ruby -Ilib -I/Users/okitan/.rvm/gems/ruby-2.0.0-p0@global/gems/bundler-1.3.4/lib -rbundler/setup -S /Users/okitan/.rvm/gems/ruby-2.0.0-p0@ci_reporter
/gems/rspec-core-2.14.7/exe/rspec --require ci/reporter/rake/rspec_loader --format CI::Reporter::RSpec acceptance/rspec_example_spec.rb
Run options: include {:wip=>true}
```

I'm a stranger of minitest, but it seems minitest 5.0.0 forbids to access runner.

See its CHANGELOG
https://github.com/seattlerb/minitest/blob/34760e3b268bc1bb4ac5fe1a44ef1ff0a2f9bd4d/History.txt#L91
